import { avagent, type Anatomy } from "./anatomy";

/**
 * The built-in character roster — proportion-only presets keyed by display name. `Avagent` is the
 * base/default; the rest are variations. These are optional — pass any to the `anatomy` prop, or roll
 * your own {@link Anatomy}. Theme (colorway) and behavior are orthogonal, so any character pairs with
 * any theme. `Stilt` is defined as an override of the base; the others are full standalone anatomies.
 */
export const characters: Record<string, Anatomy> = {
  Avagent: avagent,
  // Tall + lanky: narrow body, long legs, a reserved arm swing, a pronounced lean into travel.
  Stilt: {
    ...avagent,
    global: { ...avagent.global, shadow: { width: 56, height: 16, blur: 5, opacity: 0.24, fadeOutBodyWidths: 8 } },
    body: { ...avagent.body, width: 36, height: 84 },
    head: {
      ...avagent.head,
      width: 56,
      height: 80,
      bodyOverlap: 11,
      roundness: 16,
      turnDepthRatio: 1.08,
      tiltDepthRatio: 0.96,
      tiltRadiusGrow: 1.5,
    },
    eye: {
      ...avagent.eye,
      width: 20,
      height: 20,
      roundnessRatio: 0.3,
      topRatio: 0.45,
      sideRatio: 0.22,
      pupilInset: 5,
      tiltHeightRatio: 0.4,
      tiltPerspectivePower: 1.5,
      turnWidthRatio: 0.24,
      turnCloserInset: -0.1,
      turnFurtherInset: 0.75,
    },
    ear: { ...avagent.ear, heightRatio: 0.2 },
    antenna: { ...avagent.antenna, height: 28, signalScale: 2 },
    arm: {
      ...avagent.arm,
      upperWidth: 20,
      lowerWidth: 20,
      upperHeight: 52,
      lowerHeight: 46,
      upperAngle: 15,
      lowerAngle: -10,
    },
    leg: { ...avagent.leg, legWidth: 20, legHeight: 64, footWidth: 24, footHeight: 20, legAngle: 3, footAngle: -3 },
    gait: {
      ...avagent.gait,
      strideDeg: 20,
      armSwingDeg: 14,
      bounceHeightRatio: 0.12,
      leanDeg: 7,
      walkMsPerBodyWidth: 480,
      travelPerBodyWidth: 3.4,
      walkDropOffset: 2,
    },
    jump: { ...avagent.jump, heightBodyWidths: 6, flailSpeed: 1.0 },
    drop: { ...avagent.drop, flailSpeed: 1.5 },
  },
  // Broad-bodied tall robot: small head, oversized round eyes, a stubby antenna; slow bouncy low-hop gait.
  Scratch: {
    global: { outlineThickness: 6, shadow: { width: 80, height: 16, blur: 5, opacity: 0.24, fadeOutBodyWidths: 6 } },
    body: {
      width: 74,
      height: 74,
      radiusTop: 32,
      radiusBottom: 24,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.6 },
      turnDepthRatio: 0.84,
      chest: {
        size: 32,
        topRatio: 0.25,
        turnMinRatio: 0.15,
        crouchMinRatio: 0.6,
        turnSlideRatio: 0.35,
        crouchRise: 0.015625,
        haloOffset: 1,
        haloBlur: 0,
      },
    },
    head: {
      width: 72,
      height: 78,
      roundness: 20,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.85 },
      turnDepthRatio: 1,
      tiltDepthRatio: 0.92,
      turnRadiusGrow: 1.1,
      tiltRadiusGrow: 1.25,
      shading: { highlightRatio: 0.5, shadowCrescentRatio: 0.5 },
      bodyOverlap: 17,
    },
    antenna: {
      width: 12,
      height: 32,
      radius: 4,
      restLean: -25,
      pivot: { xFrac: 0.5, yFrac: 1 },
      baseInset: 10,
      rightRatio: 0.15,
      tiltHeightRatio: 0.5,
      signalScale: 2.5,
    },
    eye: {
      width: 42,
      height: 42,
      roundnessRatio: 0.2,
      pivot: { xFrac: 0.5, yFrac: 0.5 },
      topRatio: 0.35,
      sideRatio: -0.04,
      turnCloserInset: -0.22333333333333333,
      turnFurtherInset: 0.6566666666666666,
      pupilInset: 0,
      turnWidthRatio: 0.6,
      tiltHeightRatio: 0.8,
      tiltPerspectivePower: 3,
    },
    ear: { topRatio: 0.4, heightRatio: 0.44, roundnessRatio: 0.4 },
    arm: {
      upperWidth: 28,
      upperHeight: 54,
      lowerWidth: 28,
      lowerHeight: 44,
      upperAngle: 25,
      lowerAngle: -15,
      shoulderRatio: 0.1,
    },
    leg: {
      legWidth: 28,
      legHeight: 54,
      footWidth: 36,
      footHeight: 28,
      legAngle: 4,
      footAngle: -4,
      hipInsetRatio: 0.13,
      hipTuckRatio: 0.40625,
    },
    speech: { gap: 19, maxWidth: 192 },
    gait: {
      strideDeg: 32,
      armSwingDeg: 22,
      bounceHeightRatio: 0.2,
      leanDeg: 4,
      walkDropOffset: 2,
      walkMsPerBodyWidth: 440,
      travelPerBodyWidth: 1.6,
    },
    jump: { heightBodyWidths: 2, flailSpeed: 0.6 },
    drop: { flailSpeed: 2.5 },
  },
  // Legless floater: zero leg/foot width, no walk bounce or arm swing, a slim body and a quick glide.
  Float: {
    global: { outlineThickness: 6, shadow: { width: 56, height: 12, blur: 3, opacity: 0.24, fadeOutBodyWidths: 4 } },
    body: {
      width: 42,
      height: 72,
      radiusTop: 12,
      radiusBottom: 21,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.6 },
      turnDepthRatio: 0.84,
      chest: {
        size: 32,
        topRatio: 0.25,
        turnMinRatio: 0.15,
        crouchMinRatio: 0.6,
        turnSlideRatio: 0.3076923076923077,
        crouchRise: 0.015625,
        haloOffset: 1,
        haloBlur: 0,
      },
    },
    head: {
      width: 96,
      height: 90,
      roundness: 32,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.85 },
      turnDepthRatio: 0.88,
      tiltDepthRatio: 0.92,
      turnRadiusGrow: 1.1,
      tiltRadiusGrow: 1.25,
      shading: { highlightRatio: 0.5, shadowCrescentRatio: 0.5 },
      bodyOverlap: 17,
    },
    antenna: {
      width: 7,
      height: 38,
      radius: 2,
      restLean: -5,
      pivot: { xFrac: 0.5, yFrac: 1 },
      baseInset: 10,
      rightRatio: 0.15,
      tiltHeightRatio: 0.5,
      signalScale: 1,
    },
    eye: {
      width: 41,
      height: 17,
      roundnessRatio: 0.5,
      pivot: { xFrac: 0.44, yFrac: 0.5 },
      topRatio: 0.44,
      sideRatio: 0.16,
      turnCloserInset: 0.12,
      turnFurtherInset: 0.6,
      pupilInset: 5,
      turnWidthRatio: 0.44,
      tiltHeightRatio: 0.7,
      tiltPerspectivePower: 3,
    },
    ear: { topRatio: 0.45, heightRatio: 0.3, roundnessRatio: 0.25 },
    arm: {
      upperWidth: 22,
      upperHeight: 48,
      lowerWidth: 20,
      lowerHeight: 40,
      upperAngle: 15,
      lowerAngle: -5,
      shoulderRatio: 0.05,
    },
    leg: {
      legWidth: 0,
      legHeight: 44,
      footWidth: 0,
      footHeight: 24,
      legAngle: 9,
      footAngle: -9,
      hipInsetRatio: 0,
      hipTuckRatio: 0.40625,
    },
    speech: { gap: 19, maxWidth: 192 },
    gait: {
      strideDeg: 40,
      armSwingDeg: 0,
      bounceHeightRatio: 0,
      leanDeg: 7,
      walkDropOffset: 0,
      walkMsPerBodyWidth: 160,
      travelPerBodyWidth: 2.2,
    },
    jump: { heightBodyWidths: 6, flailSpeed: 0.1 },
    drop: { flailSpeed: 2.5 },
  },
  // Tall + slim, wide flat head with thin slot eyes; long springy legs, fast skittery glide.
  Glitch: {
    global: { outlineThickness: 6, shadow: { width: 56, height: 16, blur: 5, opacity: 0.24, fadeOutBodyWidths: 8 } },
    body: {
      width: 32,
      height: 72,
      radiusTop: 24,
      radiusBottom: 4,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.6 },
      turnDepthRatio: 0.84,
      chest: {
        size: 32,
        topRatio: 0.25,
        turnMinRatio: 0.15,
        crouchMinRatio: 0.6,
        turnSlideRatio: 0.3076923076923077,
        crouchRise: 0.015625,
        haloOffset: 1,
        haloBlur: 0,
      },
    },
    head: {
      width: 90,
      height: 48,
      roundness: 24,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.85 },
      turnDepthRatio: 0.64,
      tiltDepthRatio: 0.96,
      turnRadiusGrow: 1.4,
      tiltRadiusGrow: 1.5,
      shading: { highlightRatio: 0.5, shadowCrescentRatio: 0.5 },
      bodyOverlap: 11,
    },
    antenna: {
      width: 8,
      height: 36,
      radius: 3,
      restLean: -15,
      pivot: { xFrac: 0.5, yFrac: 1 },
      baseInset: 10,
      rightRatio: 0.15,
      tiltHeightRatio: 0.5,
      signalScale: 2,
    },
    eye: {
      width: 36,
      height: 14,
      roundnessRatio: 0.1,
      pivot: { xFrac: 0.5, yFrac: 0.5 },
      topRatio: 0.45,
      sideRatio: 0.12,
      turnCloserInset: 0.1,
      turnFurtherInset: 0.6,
      pupilInset: 5,
      turnWidthRatio: 0.24,
      tiltHeightRatio: 0.4,
      tiltPerspectivePower: 1.5,
    },
    ear: { topRatio: 0.42, heightRatio: 0.4, roundnessRatio: 0.3 },
    arm: {
      upperWidth: 18,
      upperHeight: 54,
      lowerWidth: 18,
      lowerHeight: 44,
      upperAngle: 15,
      lowerAngle: -10,
      shoulderRatio: 0.05,
    },
    leg: {
      legWidth: 18,
      legHeight: 64,
      footWidth: 24,
      footHeight: 16,
      legAngle: 3,
      footAngle: -3,
      hipInsetRatio: 0.1,
      hipTuckRatio: 0.40625,
    },
    speech: { gap: 19, maxWidth: 192 },
    gait: {
      strideDeg: 30,
      armSwingDeg: 24,
      bounceHeightRatio: 0.2,
      leanDeg: 7,
      walkDropOffset: 2,
      walkMsPerBodyWidth: 480,
      travelPerBodyWidth: 3.9,
    },
    jump: { heightBodyWidths: 4.5, flailSpeed: 0.4 },
    drop: { flailSpeed: 1.5 },
  },
  // Broad-bodied with a big boxy near-square head and oversized eyes; a high, snappy jump.
  Loop: {
    global: { outlineThickness: 6, shadow: { width: 80, height: 16, blur: 5, opacity: 0.24, fadeOutBodyWidths: 6 } },
    body: {
      width: 40,
      height: 55,
      radiusTop: 12,
      radiusBottom: 12,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.6 },
      turnDepthRatio: 0.84,
      chest: {
        size: 32,
        topRatio: 0.25,
        turnMinRatio: 0.15,
        crouchMinRatio: 0.6,
        turnSlideRatio: 0.35,
        crouchRise: 0.015625,
        haloOffset: 1,
        haloBlur: 0,
      },
    },
    head: {
      width: 96,
      height: 103,
      roundness: 12,
      restRotation: 0,
      pivot: { xFrac: 0.5, yFrac: 0.85 },
      turnDepthRatio: 1,
      tiltDepthRatio: 0.92,
      turnRadiusGrow: 1.4,
      tiltRadiusGrow: 1.25,
      shading: { highlightRatio: 0.5, shadowCrescentRatio: 0.5 },
      bodyOverlap: 17,
    },
    antenna: {
      width: 8,
      height: 44,
      radius: 4,
      restLean: -25,
      pivot: { xFrac: 0.5, yFrac: 1 },
      baseInset: 10,
      rightRatio: 0.15,
      tiltHeightRatio: 0.5,
      signalScale: 2.5,
    },
    eye: {
      width: 48,
      height: 44,
      roundnessRatio: 0.2,
      pivot: { xFrac: 0.5, yFrac: 0.5 },
      topRatio: 0.45,
      sideRatio: 0.04,
      turnCloserInset: -0.22333333333333333,
      turnFurtherInset: 0.6566666666666666,
      pupilInset: 18,
      turnWidthRatio: 0.6,
      tiltHeightRatio: 0.8,
      tiltPerspectivePower: 3,
    },
    ear: { topRatio: 0.4, heightRatio: 0.34, roundnessRatio: 0.4 },
    arm: {
      upperWidth: 20,
      upperHeight: 54,
      lowerWidth: 20,
      lowerHeight: 44,
      upperAngle: 10,
      lowerAngle: -5,
      shoulderRatio: 0.1,
    },
    leg: {
      legWidth: 20,
      legHeight: 64,
      footWidth: 28,
      footHeight: 22,
      legAngle: 2,
      footAngle: -2,
      hipInsetRatio: -0.01,
      hipTuckRatio: 0.40625,
    },
    speech: { gap: 19, maxWidth: 192 },
    gait: {
      strideDeg: 32,
      armSwingDeg: 22,
      bounceHeightRatio: 0.2,
      leanDeg: 4,
      walkDropOffset: 2,
      walkMsPerBodyWidth: 360,
      travelPerBodyWidth: 2.6,
    },
    jump: { heightBodyWidths: 4, flailSpeed: 1.6 },
    drop: { flailSpeed: 2.5 },
  },
};
